FROM ubuntu:24.04
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential git wget python3 python3-pip python-is-python3 ca-certificates && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --break-system-packages --disable-pip-version-check --no-cache-dir -r requirements.txt

COPY . /app
