version: "3.9"
services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  docs-search-app:
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          path: .
    container_name: docs-search-app
    depends_on:
      - qdrant
    environment:
      QDRANT_URL: "http://qdrant:6333"
      DOCS_DIR: "/app/docs"
      EMBEDDING_MODEL: "all-MiniLM-L6-v2"
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - ./docs:/app/docs
      - ./static:/app/static

volumes:
  qdrant_storage:
